# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnimeInfoWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 566)
        self.AnimeCover = QtWidgets.QLabel(Dialog)
        self.AnimeCover.setGeometry(QtCore.QRect(20, 20, 194, 274))
        self.AnimeCover.setText("")
        self.AnimeCover.setScaledContents(True)
        self.AnimeCover.setWordWrap(False)
        self.AnimeCover.setObjectName("AnimeCover")
        self.AnimeTitle = QtWidgets.QLabel(Dialog)
        self.AnimeTitle.setGeometry(QtCore.QRect(230, 24, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.AnimeTitle.setFont(font)
        self.AnimeTitle.setScaledContents(False)
        self.AnimeTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.AnimeTitle.setWordWrap(True)
        self.AnimeTitle.setObjectName("AnimeTitle")
        self.AnimeEps = QtWidgets.QListWidget(Dialog)
        self.AnimeEps.setEnabled(False)
        self.AnimeEps.setGeometry(QtCore.QRect(20, 315, 101, 231))
        self.AnimeEps.setObjectName("AnimeEps")
        self.AnimeDesc = QtWidgets.QLabel(Dialog)
        self.AnimeDesc.setGeometry(QtCore.QRect(230, 80, 251, 211))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.AnimeDesc.setFont(font)
        self.AnimeDesc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.AnimeDesc.setWordWrap(True)
        self.AnimeDesc.setObjectName("AnimeDesc")
        self.AnimeQuality = QtWidgets.QListWidget(Dialog)
        self.AnimeQuality.setEnabled(False)
        self.AnimeQuality.setGeometry(QtCore.QRect(140, 315, 111, 231))
        self.AnimeQuality.setObjectName("AnimeQuality")
        self.StreamingBtn = QtWidgets.QPushButton(Dialog)
        self.StreamingBtn.setEnabled(False)
        self.StreamingBtn.setGeometry(QtCore.QRect(260, 315, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.StreamingBtn.setFont(font)
        self.StreamingBtn.setObjectName("StreamingBtn")
        self.DownloadBtn = QtWidgets.QPushButton(Dialog)
        self.DownloadBtn.setEnabled(False)
        self.DownloadBtn.setGeometry(QtCore.QRect(260, 370, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.DownloadBtn.setFont(font)
        self.DownloadBtn.setObjectName("DownloadBtn")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 425, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.downloadURL = QtWidgets.QPlainTextEdit(Dialog)
        self.downloadURL.setGeometry(QtCore.QRect(260, 484, 221, 61))
        self.downloadURL.setReadOnly(True)
        self.downloadURL.setObjectName("downloadURL")

        self.retranslateUi(Dialog)
        self.AnimeEps.setCurrentRow(-1)
        self.AnimeQuality.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.AnimeQuality.setSortingEnabled(False)
        self.StreamingBtn.setText(_translate("Dialog", "Streaming"))
        self.DownloadBtn.setText(_translate("Dialog", "Download"))
        self.pushButton_3.setText(_translate("Dialog", "Download Batch"))
        self.downloadURL.setPlaceholderText(_translate("Dialog", "Download URL"))
