# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnimeInfoWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(720, 700)
        Dialog.setStyleSheet("background-color: #FFF;")
        self.AnimeCover = QtWidgets.QLabel(Dialog)
        self.AnimeCover.setGeometry(QtCore.QRect(20, 20, 194, 274))
        self.AnimeCover.setScaledContents(True)
        self.AnimeCover.setObjectName("AnimeCover")
        self.AnimeTitle = QtWidgets.QLabel(Dialog)
        self.AnimeTitle.setGeometry(QtCore.QRect(230, 20, 391, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.AnimeTitle.setFont(font)
        self.AnimeTitle.setText("")
        self.AnimeTitle.setScaledContents(False)
        self.AnimeTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AnimeTitle.setWordWrap(True)
        self.AnimeTitle.setObjectName("AnimeTitle")
        self.AnimeEps = QtWidgets.QListWidget(Dialog)
        self.AnimeEps.setEnabled(True)
        self.AnimeEps.setGeometry(QtCore.QRect(20, 310, 270, 180))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.AnimeEps.setFont(font)
        self.AnimeEps.setStyleSheet("position: absolute;\n"
"background: #F4F4F4;\n"
"border-radius: 8px;")
        self.AnimeEps.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.AnimeEps.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.AnimeEps.setGridSize(QtCore.QSize(25, 25))
        self.AnimeEps.setObjectName("AnimeEps")
        self.StreamingBtn = QtWidgets.QPushButton(Dialog)
        self.StreamingBtn.setEnabled(False)
        self.StreamingBtn.setGeometry(QtCore.QRect(20, 570, 270, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.StreamingBtn.setFont(font)
        self.StreamingBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.StreamingBtn.setStyleSheet("padding: 12px 8px;\n"
"position: absolute;\n"
"background: #2D2D2D;\n"
"border-radius: 4px;\n"
"color: #FFFFFF;")
        self.StreamingBtn.setObjectName("StreamingBtn")
        self.DownloadBtn = QtWidgets.QPushButton(Dialog)
        self.DownloadBtn.setEnabled(False)
        self.DownloadBtn.setGeometry(QtCore.QRect(20, 630, 270, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DownloadBtn.setFont(font)
        self.DownloadBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DownloadBtn.setStyleSheet("padding: 12px 8px;\n"
"position: absolute;\n"
"border: 1px solid rgba(45, 45, 45, 0.6);\n"
"border-radius: 4px;\n"
"color: #000;\n"
"background: #ccc;")
        self.DownloadBtn.setObjectName("DownloadBtn")
        self.firstQuality = QtWidgets.QPushButton(Dialog)
        self.firstQuality.setGeometry(QtCore.QRect(20, 510, 57, 37))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.firstQuality.setFont(font)
        self.firstQuality.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.firstQuality.setStyleSheet("position: absolute;\n"
"background: #fff;\n"
"border-radius: 8px;\n"
"text-align: center;\n"
"color: #FFF;")
        self.firstQuality.setObjectName("firstQuality")
        self.secondQuality = QtWidgets.QPushButton(Dialog)
        self.secondQuality.setGeometry(QtCore.QRect(90, 510, 57, 37))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.secondQuality.setFont(font)
        self.secondQuality.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.secondQuality.setStyleSheet("position: absolute;\n"
"background: #FFF;\n"
"border-radius: 8px;\n"
"text-align: center;\n"
"color: #FFF;")
        self.secondQuality.setObjectName("secondQuality")
        self.thirdQuality = QtWidgets.QPushButton(Dialog)
        self.thirdQuality.setGeometry(QtCore.QRect(160, 510, 57, 37))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.thirdQuality.setFont(font)
        self.thirdQuality.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.thirdQuality.setStyleSheet("position: absolute;\n"
"background: #FFF;\n"
"border-radius: 8px;\n"
"text-align: center;\n"
"color: #FFF;")
        self.thirdQuality.setObjectName("thirdQuality")
        self.fourthQuality = QtWidgets.QPushButton(Dialog)
        self.fourthQuality.setGeometry(QtCore.QRect(230, 510, 57, 37))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.fourthQuality.setFont(font)
        self.fourthQuality.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fourthQuality.setStyleSheet("position: absolute;\n"
"background: #FFF;\n"
"border-radius: 8px;\n"
"text-align: center;\n"
"color: #FFF;")
        self.fourthQuality.setObjectName("fourthQuality")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(230, 190, 470, 100))
        self.widget.setStyleSheet("background: #FAFAFA;\n"
"border-radius: 16px;")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(64, 20, 32, 32))
        self.label.setPixmap(QtGui.QPixmap(":/icons/img/studio.svg"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.infoStudio = QtWidgets.QLabel(self.widget)
        self.infoStudio.setGeometry(QtCore.QRect(36, 50, 91, 40))
        self.infoStudio.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.infoStudio.setFont(font)
        self.infoStudio.setText("")
        self.infoStudio.setScaledContents(True)
        self.infoStudio.setAlignment(QtCore.Qt.AlignCenter)
        self.infoStudio.setWordWrap(True)
        self.infoStudio.setObjectName("infoStudio")
        self.infoType = QtWidgets.QLabel(self.widget)
        self.infoType.setGeometry(QtCore.QRect(140, 50, 91, 40))
        self.infoType.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.infoType.setFont(font)
        self.infoType.setText("")
        self.infoType.setScaledContents(True)
        self.infoType.setAlignment(QtCore.Qt.AlignCenter)
        self.infoType.setWordWrap(True)
        self.infoType.setObjectName("infoType")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(169, 20, 32, 32))
        self.label_4.setPixmap(QtGui.QPixmap(":/icons/img/clock.svg"))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.infoGenre = QtWidgets.QLabel(self.widget)
        self.infoGenre.setGeometry(QtCore.QRect(245, 50, 85, 40))
        self.infoGenre.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.infoGenre.setFont(font)
        self.infoGenre.setText("")
        self.infoGenre.setScaledContents(True)
        self.infoGenre.setAlignment(QtCore.Qt.AlignCenter)
        self.infoGenre.setWordWrap(True)
        self.infoGenre.setObjectName("infoGenre")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(269, 20, 32, 32))
        self.label_6.setPixmap(QtGui.QPixmap(":/icons/img/genre.svg"))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.infoStatus = QtWidgets.QLabel(self.widget)
        self.infoStatus.setGeometry(QtCore.QRect(360, 50, 80, 40))
        self.infoStatus.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.infoStatus.setFont(font)
        self.infoStatus.setText("")
        self.infoStatus.setScaledContents(True)
        self.infoStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.infoStatus.setWordWrap(True)
        self.infoStatus.setObjectName("infoStatus")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(385, 20, 32, 32))
        self.label_8.setPixmap(QtGui.QPixmap(":/icons/img/status.svg"))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.totalEpisode = QtWidgets.QLabel(Dialog)
        self.totalEpisode.setGeometry(QtCore.QRect(230, 90, 201, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.totalEpisode.setFont(font)
        self.totalEpisode.setStyleSheet("position: absolute;\n"
"width: 139px;\n"
"height: 22px;\n"
"left: 318px;\n"
"top: 102px;\n"
"\n"
"color: #3E3E3E;")
        self.totalEpisode.setText("")
        self.totalEpisode.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.totalEpisode.setObjectName("totalEpisode")
        self.star1 = QtWidgets.QLabel(Dialog)
        self.star1.setGeometry(QtCore.QRect(230, 120, 24, 24))
        self.star1.setStyleSheet("width: 30px;\n"
"height: 30px;\n"
"left: 318px;\n"
"top: 132px;\n"
"border-radius: 2px;\n"
"border-image: url(:/icons/img/star_off.svg);")
        self.star1.setScaledContents(True)
        self.star1.setObjectName("star1")
        self.star2 = QtWidgets.QLabel(Dialog)
        self.star2.setGeometry(QtCore.QRect(260, 120, 24, 24))
        self.star2.setStyleSheet("width: 30px;\n"
"height: 30px;\n"
"left: 318px;\n"
"top: 132px;\n"
"border-radius: 2px;\n"
"border-image: url(:/icons/img/star_off.svg);")
        self.star2.setScaledContents(True)
        self.star2.setObjectName("star2")
        self.star3 = QtWidgets.QLabel(Dialog)
        self.star3.setGeometry(QtCore.QRect(290, 120, 24, 24))
        self.star3.setStyleSheet("width: 30px;\n"
"height: 30px;\n"
"left: 318px;\n"
"top: 132px;\n"
"border-radius: 2px;\n"
"border-image: url(:/icons/img/star_off.svg);")
        self.star3.setScaledContents(True)
        self.star3.setObjectName("star3")
        self.star4 = QtWidgets.QLabel(Dialog)
        self.star4.setGeometry(QtCore.QRect(320, 120, 24, 24))
        self.star4.setStyleSheet("width: 30px;\n"
"height: 30px;\n"
"left: 318px;\n"
"top: 132px;\n"
"border-radius: 2px;\n"
"border-image: url(:/icons/img/star_off.svg);")
        self.star4.setScaledContents(True)
        self.star4.setObjectName("star4")
        self.star5 = QtWidgets.QLabel(Dialog)
        self.star5.setGeometry(QtCore.QRect(350, 120, 24, 24))
        self.star5.setStyleSheet("width: 30px;\n"
"height: 30px;\n"
"left: 318px;\n"
"top: 132px;\n"
"border-radius: 2px;\n"
"border-image: url(:/icons/img/star_off.svg);")
        self.star5.setScaledContents(True)
        self.star5.setObjectName("star5")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(310, 310, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.AnimeSinopsis = QtWidgets.QLabel(Dialog)
        self.AnimeSinopsis.setGeometry(QtCore.QRect(310, 340, 390, 150))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.AnimeSinopsis.setFont(font)
        self.AnimeSinopsis.setText("")
        self.AnimeSinopsis.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.AnimeSinopsis.setWordWrap(True)
        self.AnimeSinopsis.setObjectName("AnimeSinopsis")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(310, 510, 201, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.recommendList = QtWidgets.QListWidget(Dialog)
        self.recommendList.setGeometry(QtCore.QRect(308, 540, 392, 140))
        self.recommendList.setStyleSheet("position: absolute;\n"
"background: #F4F4F4;\n"
"border-radius: 8px;")
        self.recommendList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.recommendList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.recommendList.setIconSize(QtCore.QSize(120, 120))
        self.recommendList.setFlow(QtWidgets.QListView.TopToBottom)
        self.recommendList.setViewMode(QtWidgets.QListView.IconMode)
        self.recommendList.setObjectName("recommendList")
        self.saveThis = QtWidgets.QPushButton(Dialog)
        self.saveThis.setGeometry(QtCore.QRect(640, 20, 60, 60))
        self.saveThis.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveThis.setStyleSheet("padding: 12px 8px;\n"
"position: absolute;\n"
"border: 1px solid rgba(45, 45, 45, 0.3);\n"
"border-radius: 4px;\n"
"color: #000;\n"
"background: #fff;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/img/bookmark_outline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveThis.setIcon(icon)
        self.saveThis.setIconSize(QtCore.QSize(32, 32))
        self.saveThis.setObjectName("saveThis")

        self.retranslateUi(Dialog)
        self.AnimeEps.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.AnimeCover.setWhatsThis(_translate("Dialog", "Cover anime"))
        self.AnimeTitle.setWhatsThis(_translate("Dialog", "Judul anime"))
        self.AnimeEps.setWhatsThis(_translate("Dialog", "Episode yang tersedia"))
        self.StreamingBtn.setWhatsThis(_translate("Dialog", "Streaming anime dengan MPV"))
        self.StreamingBtn.setText(_translate("Dialog", "Streaming"))
        self.DownloadBtn.setWhatsThis(_translate("Dialog", "Download anime dengan membuka browser"))
        self.DownloadBtn.setText(_translate("Dialog", "Download"))
        self.firstQuality.setWhatsThis(_translate("Dialog", "Kualitas anime untuk download atau streaming anime"))
        self.firstQuality.setText(_translate("Dialog", "360p"))
        self.secondQuality.setWhatsThis(_translate("Dialog", "Kualitas anime untuk download atau streaming anime"))
        self.secondQuality.setText(_translate("Dialog", "480p"))
        self.thirdQuality.setWhatsThis(_translate("Dialog", "Kualitas anime untuk download atau streaming anime"))
        self.thirdQuality.setText(_translate("Dialog", "720p"))
        self.fourthQuality.setWhatsThis(_translate("Dialog", "Kualitas anime untuk download atau streaming anime"))
        self.fourthQuality.setText(_translate("Dialog", "1080p"))
        self.widget.setWhatsThis(_translate("Dialog", "Info anime"))
        self.totalEpisode.setWhatsThis(_translate("Dialog", "Jumlah episode, mungkin akan bertambah seiring waktu"))
        self.star1.setWhatsThis(_translate("Dialog", "Rating anime"))
        self.star2.setWhatsThis(_translate("Dialog", "Rating anime"))
        self.star3.setWhatsThis(_translate("Dialog", "Rating anime"))
        self.star4.setWhatsThis(_translate("Dialog", "Rating anime"))
        self.star5.setWhatsThis(_translate("Dialog", "Rating anime"))
        self.label_15.setText(_translate("Dialog", "Sinopsis"))
        self.AnimeSinopsis.setWhatsThis(_translate("Dialog", "Sinopsis"))
        self.label_17.setText(_translate("Dialog", "Rekomendasi Serupa"))
        self.recommendList.setWhatsThis(_translate("Dialog", "List rekomendasi anime"))
import resources_rc
