# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 381, 241))
        self.groupBox.setObjectName("groupBox")
        self.mpvCustomPath = QtWidgets.QLineEdit(self.groupBox)
        self.mpvCustomPath.setGeometry(QtCore.QRect(70, 20, 221, 21))
        self.mpvCustomPath.setObjectName("mpvCustomPath")
        self.mpvBrowse = QtWidgets.QPushButton(self.groupBox)
        self.mpvBrowse.setGeometry(QtCore.QRect(300, 20, 75, 23))
        self.mpvBrowse.setObjectName("mpvBrowse")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 47, 21))
        self.label.setObjectName("label")
        self.testMPV = QtWidgets.QPushButton(Dialog)
        self.testMPV.setGeometry(QtCore.QRect(10, 260, 75, 23))
        self.testMPV.setObjectName("testMPV")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 260, 71, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.saveConfig = QtWidgets.QPushButton(Dialog)
        self.saveConfig.setGeometry(QtCore.QRect(240, 260, 71, 23))
        self.saveConfig.setObjectName("saveConfig")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Pengaturan"))
        self.groupBox.setTitle(_translate("Dialog", "Path Environment"))
        self.mpvCustomPath.setPlaceholderText(_translate("Dialog", "Default"))
        self.mpvBrowse.setText(_translate("Dialog", "Browse"))
        self.label.setText(_translate("Dialog", "MPV Path: "))
        self.testMPV.setText(_translate("Dialog", "Test MPV"))
        self.pushButton_2.setText(_translate("Dialog", "Cancel"))
        self.saveConfig.setText(_translate("Dialog", "Save"))
