# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'About.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.devProfilePic = QtWidgets.QLabel(Dialog)
        self.devProfilePic.setGeometry(QtCore.QRect(20, 20, 120, 120))
        self.devProfilePic.setText("")
        self.devProfilePic.setPixmap(QtGui.QPixmap("../../../../../Pictures/Me/1668922110114900120_99.jpg"))
        self.devProfilePic.setScaledContents(True)
        self.devProfilePic.setObjectName("devProfilePic")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(160, 20, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.closeBtn = QtWidgets.QPushButton(Dialog)
        self.closeBtn.setGeometry(QtCore.QRect(314, 220, 60, 60))
        self.closeBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/close.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeBtn.setIcon(icon)
        self.closeBtn.setIconSize(QtCore.QSize(24, 24))
        self.closeBtn.setObjectName("closeBtn")
        self.githubBtn = QtWidgets.QPushButton(Dialog)
        self.githubBtn.setGeometry(QtCore.QRect(240, 220, 60, 60))
        self.githubBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/github.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.githubBtn.setIcon(icon1)
        self.githubBtn.setIconSize(QtCore.QSize(32, 32))
        self.githubBtn.setObjectName("githubBtn")
        self.donateBtn = QtWidgets.QPushButton(Dialog)
        self.donateBtn.setGeometry(QtCore.QRect(165, 220, 60, 60))
        self.donateBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/kofi.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.donateBtn.setIcon(icon2)
        self.donateBtn.setIconSize(QtCore.QSize(32, 32))
        self.donateBtn.setObjectName("donateBtn")
        self.aboutSource = QtWidgets.QLabel(Dialog)
        self.aboutSource.setGeometry(QtCore.QRect(160, 60, 221, 81))
        self.aboutSource.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.aboutSource.setObjectName("aboutSource")
        self.devProfileName = QtWidgets.QLabel(Dialog)
        self.devProfileName.setGeometry(QtCore.QRect(20, 135, 121, 31))
        self.devProfileName.setAlignment(QtCore.Qt.AlignCenter)
        self.devProfileName.setObjectName("devProfileName")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "PyAnimeIndo"))
        self.aboutSource.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:696;\">Data Host: </span><a href=\"https://otakudesu.pro\"><span style=\" text-decoration: underline; color:#0000ff;\">otakudesu.pro</span></a></p><p><span style=\" font-weight:600;\">Video Player: </span><a href=\"https://github.com/mpv-player/mpv\"><span style=\" text-decoration: underline; color:#0000ff;\">mpv-player</span></a></p><p><span style=\" font-weight:600;\">Python version:</span> __pythonVer__</p></body></html>"))
        self.devProfileName.setText(_translate("Dialog", "Ayra Hikari"))
